services:
  - type: worker
    name: sirion-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh start.sh
  - type: web
    name: sirion-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
